"""Generate monthly SEO report PDF bytes."""

from __future__ import annotations

import io
from datetime import datetime
from typing import Any


def _fmt_num(v: Any) -> str:
    if v is None:
        return "—"
    if isinstance(v, float):
        return str(int(v)) if v == int(v) else f"{v:.1f}"
    return str(v)


def render_monthly_report_pdf(
    *,
    business_name: str,
    month_label: str,
    keyword: str,
    report: dict,
) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=0.65 * inch,
        leftMargin=0.65 * inch,
        topMargin=0.6 * inch,
        bottomMargin=0.6 * inch,
        title=f"Monthly SEO Report — {month_label}",
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Heading1"],
        fontSize=20,
        textColor=colors.HexColor("#0F172A"),
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "ReportSubtitle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#64748B"),
        spaceAfter=16,
    )
    section_style = ParagraphStyle(
        "Section",
        parent=styles["Heading2"],
        fontSize=12,
        textColor=colors.HexColor("#0F172A"),
        spaceBefore=12,
        spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#334155"),
    )
    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.HexColor("#94A3B8"),
    )

    vis_start = report.get("visibility_score_start")
    vis_end = report.get("visibility_score_end")
    score_delta = ""
    if vis_start is not None and vis_end is not None:
        d = float(vis_end) - float(vis_start)
        score_delta = f" ({'+' if d >= 0 else ''}{d:.1f} pts)"

    metrics = [
        ["Metric", "Value", "Notes"],
        [
            "Visibility score",
            _fmt_num(vis_end),
            f"Start: {_fmt_num(vis_start)}{score_delta}",
        ],
        [
            "Top-3 suburbs",
            _fmt_num(report.get("top3_end")),
            f"Start of month: {_fmt_num(report.get('top3_start'))}",
        ],
        ["Pages published", _fmt_num(report.get("pages_published")), ""],
        ["GBP posts published", _fmt_num(report.get("gbp_posts")), ""],
        ["Citations verified", _fmt_num(report.get("citations_fixed")), ""],
        ["New reviews", _fmt_num(report.get("reviews_new")), ""],
    ]

    table = Table(metrics, colWidths=[2.2 * inch, 1.2 * inch, 2.6 * inch])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F172A")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 9),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
                ("TOPPADDING", (0, 0), (-1, 0), 8),
                ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#F8FAFC")),
                ("TEXTCOLOR", (0, 1), (-1, -1), colors.HexColor("#334155")),
                ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 1), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 1), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 1), (-1, -1), 6),
            ]
        )
    )

    narrative = str(report.get("narrative_text") or "").replace("\n", "<br/>")
    bname = (business_name or "Your business").strip()
    kw = (keyword or "—").strip()

    story = [
        Paragraph("Monthly SEO Report", title_style),
        Paragraph(f"{bname} · {month_label}", subtitle_style),
        Paragraph(f"Primary keyword: <b>{kw}</b>", body_style),
        Spacer(1, 0.15 * inch),
        Paragraph("Key metrics", section_style),
        table,
        Spacer(1, 0.1 * inch),
        Paragraph("Summary", section_style),
        Paragraph(narrative or "No summary available for this period.", body_style),
        Spacer(1, 0.25 * inch),
        Paragraph(
            f"Generated by RankPilot · {datetime.now().strftime('%d %b %Y %H:%M UTC')}",
            footer_style,
        ),
    ]

    doc.build(story)
    return buf.getvalue()
