import { Link } from "react-router-dom";

const SECTIONS = [
  {
    title: "1. Who We Are",
    body: `RankPilot is a local SEO automation platform operated by Traffic Radius Pty Ltd ("we", "us", "our").
We help small businesses track their Google Maps visibility, manage citations, and improve local search rankings.
If you have questions about this policy, contact us at privacy@trafficradius.com.au.`,
  },
  {
    title: "2. Information We Collect",
    body: `We collect the following types of information:

• Account data — your email address and credentials when you register.
• Business data — your business name, website URL, address, phone number, and service keyword that you provide during onboarding.
• Google Business Profile (GBP) data — if you connect your GBP account, we access location data, posts, Q&A, and review information via the Google API.
• Usage data — pages visited, features used, and interaction timestamps within the app.
• Scan results — Google Maps rank positions, competitor data, and suburb visibility scores generated by DataForSEO on your behalf.`,
  },
  {
    title: "3. How We Use Your Information",
    body: `We use your information to:

• Provide, operate, and improve the RankPilot service.
• Perform Google Maps rank scans and generate SEO reports for your business.
• Send transactional emails (scan results, report notifications).
• Display your business details and citation data accurately across the platform.
• Diagnose technical issues and ensure platform security.

We do not sell your personal information to third parties.`,
  },
  {
    title: "4. Third-Party Services",
    body: `RankPilot uses the following third-party services to deliver its features:

• DataForSEO — for Google Maps rank data, keyword volumes, and Google Business review data.
• Google Places API — to resolve canonical business details (name, address, phone).
• Firecrawl — to scrape public directory listings for citation auditing.
• Anthropic Claude / OpenAI — for AI-drafted content and review response suggestions.
• Stripe — for billing and subscription management (if applicable).

Each provider has its own privacy policy. We recommend reviewing them separately.`,
  },
  {
    title: "5. Data Storage & Security",
    body: `Your data is stored in a PostgreSQL database hosted on infrastructure in Australia or as specified in your service agreement.
We implement industry-standard security measures including encrypted connections (TLS), hashed passwords, and row-level security on your data.
Access tokens are stored in browser session storage and expire when your browser tab is closed.`,
  },
  {
    title: "6. Data Retention",
    body: `We retain your account and business data for as long as your account is active.
Rank history and scan data is retained for a rolling 12-month period unless you request earlier deletion.
You may request deletion of your account and associated data by contacting us at privacy@trafficradius.com.au.`,
  },
  {
    title: "7. Your Rights",
    body: `Under the Australian Privacy Act 1988 and applicable state legislation, you have the right to:

• Access the personal information we hold about you.
• Request correction of inaccurate or outdated information.
• Request deletion of your data (subject to legal retention obligations).
• Opt out of non-essential communications.

To exercise any of these rights, please contact privacy@trafficradius.com.au.`,
  },
  {
    title: "8. Cookies",
    body: `RankPilot uses browser session storage (not cookies) to maintain your login state.
We do not currently use tracking cookies or third-party advertising pixels.`,
  },
  {
    title: "9. Changes to This Policy",
    body: `We may update this Privacy Policy from time to time. When we do, we will update the "Last updated" date below and notify you via email if the changes are material.
Continued use of the platform after changes are posted constitutes your acceptance of the updated policy.`,
  },
  {
    title: "10. Contact Us",
    body: `Traffic Radius Pty Ltd
Email: privacy@trafficradius.com.au
Website: https://trafficradius.com.au`,
  },
];

export function PrivacyPolicyPage() {
  return (
    <div
      className="min-h-screen px-4 py-12"
      style={{
        backgroundColor: "#EDF4DD",
        backgroundImage:
          "radial-gradient(ellipse 80% 50% at 15% 0%, rgba(114,194,25,0.15) 0%, transparent 65%), " +
          "radial-gradient(ellipse 55% 45% at 85% 100%, rgba(114,194,25,0.08) 0%, transparent 65%)",
      }}
    >
      <div className="mx-auto max-w-3xl">

        {/* Header */}
        <div className="mb-8 text-center">
          <div className="mb-2 text-2xl font-extrabold tracking-tight text-navy">
            Rank<span style={{ color: "#72C219" }}>Pilot</span>
          </div>
          <h1 className="text-[28px] font-extrabold text-navy">Privacy Policy</h1>
          <p className="mt-1 text-sm text-rp-tlight">Last updated: 29 April 2026</p>
        </div>

        {/* Intro card */}
        <div className="mb-6 rounded-[16px] border border-rp-border bg-white px-6 py-5 shadow-card">
          <p className="text-[13px] leading-relaxed text-rp-tmid">
            At Traffic Radius, we take your privacy seriously. This Privacy Policy explains what
            information we collect when you use RankPilot, how we use it, and your rights regarding
            your data. Please read it carefully before using our platform.
          </p>
        </div>

        {/* Sections */}
        <div className="space-y-4">
          {SECTIONS.map((s) => (
            <div
              key={s.title}
              className="rounded-[14px] border border-rp-border bg-white px-6 py-5 shadow-card"
            >
              <h2 className="mb-3 text-[15px] font-bold text-navy">{s.title}</h2>
              <p className="whitespace-pre-line text-[13px] leading-relaxed text-rp-tmid">
                {s.body}
              </p>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-8 text-center text-xs text-rp-tlight">
          <p>© {new Date().getFullYear()} Traffic Radius Pty Ltd · All rights reserved.</p>
          <Link
            to="/login"
            className="mt-2 inline-block font-semibold hover:underline"
            style={{ color: "#72C219" }}
          >
            ← Back to Sign In
          </Link>
        </div>

      </div>
    </div>
  );
}
